version: 1
accounts:
  - name: alice
    coins: ["10000000000001000000wrmb"]
  - name: bob
    coins: ["5000000000000000000wrmb"]
  - name: employer
    coins: ["6000000000000000000wrmb"]
  - name: developer
    coins: ["8000000000000000000wrmb"]
validators:
  - name: alice
    bonded: "1000000wrmb"
client:
  openapi:
    path: "docs/static/openapi.yml"
#  typescript:
#    path: "ts-client"
#  vuex:
#    path: "vue/src/store"
faucet:
  name: bob
  coins: ["10000wrmb"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "wrmb"
    crisis:
      constant_fee:
        denom: "wrmb"
    gov:
      deposit_params:
        min_deposit:
          -
            denom: "wrmb"
            amount: "1000"
    mint:
      params:
        mint_denom: "wrmb"
        inflation_max: "0.000000000000000000"
        inflation_min: "0.000000000000000000"
    sideline:
      params:
        minConfirmJudgeHeight: 600
        minConfirmSubmitHeight: 300

