// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sideline/sideline/employer.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Employer struct {
	Index     string   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Name      string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Introduce string   `protobuf:"bytes,3,opt,name=introduce,proto3" json:"introduce,omitempty"`
	Email     string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Avatar    string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Address   string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	TaskIds   []uint64 `protobuf:"varint,7,rep,packed,name=taskIds,proto3" json:"taskIds,omitempty"`
	Feedbacks []string `protobuf:"bytes,8,rep,name=feedbacks,proto3" json:"feedbacks,omitempty"`
}

func (m *Employer) Reset()         { *m = Employer{} }
func (m *Employer) String() string { return proto.CompactTextString(m) }
func (*Employer) ProtoMessage()    {}
func (*Employer) Descriptor() ([]byte, []int) {
	return fileDescriptor_30760f168d2f15ab, []int{0}
}
func (m *Employer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Employer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Employer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Employer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employer.Merge(m, src)
}
func (m *Employer) XXX_Size() int {
	return m.Size()
}
func (m *Employer) XXX_DiscardUnknown() {
	xxx_messageInfo_Employer.DiscardUnknown(m)
}

var xxx_messageInfo_Employer proto.InternalMessageInfo

func (m *Employer) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Employer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Employer) GetIntroduce() string {
	if m != nil {
		return m.Introduce
	}
	return ""
}

func (m *Employer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Employer) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Employer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Employer) GetTaskIds() []uint64 {
	if m != nil {
		return m.TaskIds
	}
	return nil
}

func (m *Employer) GetFeedbacks() []string {
	if m != nil {
		return m.Feedbacks
	}
	return nil
}

func init() {
	proto.RegisterType((*Employer)(nil), "sideline.sideline.Employer")
}

func init() { proto.RegisterFile("sideline/sideline/employer.proto", fileDescriptor_30760f168d2f15ab) }

var fileDescriptor_30760f168d2f15ab = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x31, 0x6b, 0xc3, 0x30,
	0x10, 0x85, 0xad, 0xda, 0x71, 0x12, 0x6d, 0x15, 0xa5, 0x5c, 0xa1, 0x08, 0xd3, 0x29, 0x53, 0x3a,
	0xe4, 0x1f, 0x14, 0x3a, 0x74, 0xcd, 0xd8, 0xed, 0x12, 0x5d, 0x41, 0xc4, 0xb6, 0x8c, 0xa4, 0x96,
	0xe4, 0x5f, 0xf4, 0x67, 0x75, 0x0c, 0x9d, 0x3a, 0x16, 0xfb, 0x8f, 0x04, 0x29, 0x91, 0xb3, 0xbd,
	0xef, 0xbd, 0xe3, 0x1e, 0x3c, 0x5e, 0x39, 0xad, 0xa8, 0xd6, 0x2d, 0x3d, 0x8f, 0x82, 0x9a, 0xae,
	0x36, 0x07, 0xb2, 0xcb, 0xce, 0x1a, 0x6f, 0xc4, 0x6d, 0x0a, 0x96, 0x49, 0x3c, 0xfd, 0x32, 0x3e,
	0x7b, 0xbd, 0x5c, 0x89, 0x3b, 0x3e, 0xd1, 0xad, 0xa2, 0x3d, 0xb0, 0x8a, 0x2d, 0xe6, 0xeb, 0x33,
	0x08, 0xc1, 0x8b, 0x16, 0x1b, 0x82, 0x9b, 0x68, 0x46, 0x2d, 0x1e, 0xf9, 0x5c, 0xb7, 0xde, 0x1a,
	0xf5, 0xb9, 0x25, 0xc8, 0x63, 0x70, 0x35, 0xc2, 0x1f, 0x6a, 0x50, 0xd7, 0x50, 0x9c, 0xff, 0x44,
	0x10, 0xf7, 0xbc, 0xc4, 0x2f, 0xf4, 0x68, 0x61, 0x12, 0xed, 0x0b, 0x09, 0xe0, 0x53, 0x54, 0xca,
	0x92, 0x73, 0x50, 0xc6, 0x20, 0x61, 0x48, 0x3c, 0xba, 0xdd, 0x9b, 0x72, 0x30, 0xad, 0xf2, 0x45,
	0xb1, 0x4e, 0x18, 0xfa, 0x3f, 0x88, 0xd4, 0x06, 0xb7, 0x3b, 0x07, 0xb3, 0x2a, 0x0f, 0xfd, 0xa3,
	0xf1, 0xb2, 0xfa, 0xe9, 0x25, 0x3b, 0xf6, 0x92, 0xfd, 0xf7, 0x92, 0x7d, 0x0f, 0x32, 0x3b, 0x0e,
	0x32, 0xfb, 0x1b, 0x64, 0xf6, 0xfe, 0x30, 0x4e, 0xb3, 0xbf, 0xae, 0xe4, 0x0f, 0x1d, 0xb9, 0x4d,
	0x19, 0x37, 0x5a, 0x9d, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x8c, 0x52, 0x36, 0x47, 0x01, 0x00,
	0x00,
}

func (m *Employer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Employer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Employer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Feedbacks) > 0 {
		for iNdEx := len(m.Feedbacks) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Feedbacks[iNdEx])
			copy(dAtA[i:], m.Feedbacks[iNdEx])
			i = encodeVarintEmployer(dAtA, i, uint64(len(m.Feedbacks[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.TaskIds) > 0 {
		dAtA2 := make([]byte, len(m.TaskIds)*10)
		var j1 int
		for _, num := range m.TaskIds {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintEmployer(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEmployer(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Avatar) > 0 {
		i -= len(m.Avatar)
		copy(dAtA[i:], m.Avatar)
		i = encodeVarintEmployer(dAtA, i, uint64(len(m.Avatar)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Email) > 0 {
		i -= len(m.Email)
		copy(dAtA[i:], m.Email)
		i = encodeVarintEmployer(dAtA, i, uint64(len(m.Email)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Introduce) > 0 {
		i -= len(m.Introduce)
		copy(dAtA[i:], m.Introduce)
		i = encodeVarintEmployer(dAtA, i, uint64(len(m.Introduce)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintEmployer(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintEmployer(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEmployer(dAtA []byte, offset int, v uint64) int {
	offset -= sovEmployer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Employer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovEmployer(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovEmployer(uint64(l))
	}
	l = len(m.Introduce)
	if l > 0 {
		n += 1 + l + sovEmployer(uint64(l))
	}
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovEmployer(uint64(l))
	}
	l = len(m.Avatar)
	if l > 0 {
		n += 1 + l + sovEmployer(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEmployer(uint64(l))
	}
	if len(m.TaskIds) > 0 {
		l = 0
		for _, e := range m.TaskIds {
			l += sovEmployer(uint64(e))
		}
		n += 1 + sovEmployer(uint64(l)) + l
	}
	if len(m.Feedbacks) > 0 {
		for _, s := range m.Feedbacks {
			l = len(s)
			n += 1 + l + sovEmployer(uint64(l))
		}
	}
	return n
}

func sovEmployer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEmployer(x uint64) (n int) {
	return sovEmployer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Employer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEmployer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Employer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Employer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmployer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmployer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmployer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmployer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmployer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmployer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Introduce", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmployer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmployer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmployer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Introduce = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmployer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmployer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmployer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Avatar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmployer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmployer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmployer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Avatar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmployer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmployer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmployer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEmployer
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.TaskIds = append(m.TaskIds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEmployer
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEmployer
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthEmployer
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.TaskIds) == 0 {
					m.TaskIds = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEmployer
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.TaskIds = append(m.TaskIds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskIds", wireType)
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feedbacks", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmployer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmployer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmployer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Feedbacks = append(m.Feedbacks, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEmployer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEmployer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEmployer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEmployer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmployer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmployer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEmployer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEmployer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEmployer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEmployer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEmployer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEmployer = fmt.Errorf("proto: unexpected end of group")
)
