// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgSuccessTask } from "./types/sideline/sideline/tx";
import { MsgSubmitTask } from "./types/sideline/sideline/tx";
import { MsgStartJudgeTask } from "./types/sideline/sideline/tx";
import { MsgCancelTask } from "./types/sideline/sideline/tx";
import { MsgDoTask } from "./types/sideline/sideline/tx";
import { MsgFailTask } from "./types/sideline/sideline/tx";
import { MsgRegistEmployer } from "./types/sideline/sideline/tx";
import { MsgCreateTask } from "./types/sideline/sideline/tx";
import { MsgUndoneTask } from "./types/sideline/sideline/tx";
import { MsgVoteTask } from "./types/sideline/sideline/tx";
import { MsgFeedbackTask } from "./types/sideline/sideline/tx";
import { MsgRegistDeveloper } from "./types/sideline/sideline/tx";
import { MsgJudgeTask } from "./types/sideline/sideline/tx";


export { MsgSuccessTask, MsgSubmitTask, MsgStartJudgeTask, MsgCancelTask, MsgDoTask, MsgFailTask, MsgRegistEmployer, MsgCreateTask, MsgUndoneTask, MsgVoteTask, MsgFeedbackTask, MsgRegistDeveloper, MsgJudgeTask };

type sendMsgSuccessTaskParams = {
  value: MsgSuccessTask,
  fee?: StdFee,
  memo?: string
};

type sendMsgSubmitTaskParams = {
  value: MsgSubmitTask,
  fee?: StdFee,
  memo?: string
};

type sendMsgStartJudgeTaskParams = {
  value: MsgStartJudgeTask,
  fee?: StdFee,
  memo?: string
};

type sendMsgCancelTaskParams = {
  value: MsgCancelTask,
  fee?: StdFee,
  memo?: string
};

type sendMsgDoTaskParams = {
  value: MsgDoTask,
  fee?: StdFee,
  memo?: string
};

type sendMsgFailTaskParams = {
  value: MsgFailTask,
  fee?: StdFee,
  memo?: string
};

type sendMsgRegistEmployerParams = {
  value: MsgRegistEmployer,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateTaskParams = {
  value: MsgCreateTask,
  fee?: StdFee,
  memo?: string
};

type sendMsgUndoneTaskParams = {
  value: MsgUndoneTask,
  fee?: StdFee,
  memo?: string
};

type sendMsgVoteTaskParams = {
  value: MsgVoteTask,
  fee?: StdFee,
  memo?: string
};

type sendMsgFeedbackTaskParams = {
  value: MsgFeedbackTask,
  fee?: StdFee,
  memo?: string
};

type sendMsgRegistDeveloperParams = {
  value: MsgRegistDeveloper,
  fee?: StdFee,
  memo?: string
};

type sendMsgJudgeTaskParams = {
  value: MsgJudgeTask,
  fee?: StdFee,
  memo?: string
};


type msgSuccessTaskParams = {
  value: MsgSuccessTask,
};

type msgSubmitTaskParams = {
  value: MsgSubmitTask,
};

type msgStartJudgeTaskParams = {
  value: MsgStartJudgeTask,
};

type msgCancelTaskParams = {
  value: MsgCancelTask,
};

type msgDoTaskParams = {
  value: MsgDoTask,
};

type msgFailTaskParams = {
  value: MsgFailTask,
};

type msgRegistEmployerParams = {
  value: MsgRegistEmployer,
};

type msgCreateTaskParams = {
  value: MsgCreateTask,
};

type msgUndoneTaskParams = {
  value: MsgUndoneTask,
};

type msgVoteTaskParams = {
  value: MsgVoteTask,
};

type msgFeedbackTaskParams = {
  value: MsgFeedbackTask,
};

type msgRegistDeveloperParams = {
  value: MsgRegistDeveloper,
};

type msgJudgeTaskParams = {
  value: MsgJudgeTask,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgSuccessTask({ value, fee, memo }: sendMsgSuccessTaskParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSuccessTask: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSuccessTask({ value: MsgSuccessTask.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSuccessTask: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSubmitTask({ value, fee, memo }: sendMsgSubmitTaskParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSubmitTask: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSubmitTask({ value: MsgSubmitTask.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSubmitTask: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgStartJudgeTask({ value, fee, memo }: sendMsgStartJudgeTaskParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgStartJudgeTask: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgStartJudgeTask({ value: MsgStartJudgeTask.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgStartJudgeTask: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCancelTask({ value, fee, memo }: sendMsgCancelTaskParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCancelTask: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCancelTask({ value: MsgCancelTask.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCancelTask: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDoTask({ value, fee, memo }: sendMsgDoTaskParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDoTask: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDoTask({ value: MsgDoTask.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDoTask: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgFailTask({ value, fee, memo }: sendMsgFailTaskParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgFailTask: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgFailTask({ value: MsgFailTask.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgFailTask: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRegistEmployer({ value, fee, memo }: sendMsgRegistEmployerParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRegistEmployer: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRegistEmployer({ value: MsgRegistEmployer.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRegistEmployer: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateTask({ value, fee, memo }: sendMsgCreateTaskParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateTask: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateTask({ value: MsgCreateTask.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateTask: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUndoneTask({ value, fee, memo }: sendMsgUndoneTaskParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUndoneTask: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUndoneTask({ value: MsgUndoneTask.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUndoneTask: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgVoteTask({ value, fee, memo }: sendMsgVoteTaskParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgVoteTask: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgVoteTask({ value: MsgVoteTask.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgVoteTask: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgFeedbackTask({ value, fee, memo }: sendMsgFeedbackTaskParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgFeedbackTask: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgFeedbackTask({ value: MsgFeedbackTask.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgFeedbackTask: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRegistDeveloper({ value, fee, memo }: sendMsgRegistDeveloperParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRegistDeveloper: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRegistDeveloper({ value: MsgRegistDeveloper.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRegistDeveloper: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgJudgeTask({ value, fee, memo }: sendMsgJudgeTaskParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgJudgeTask: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgJudgeTask({ value: MsgJudgeTask.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgJudgeTask: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgSuccessTask({ value }: msgSuccessTaskParams): EncodeObject {
			try {
				return { typeUrl: "/sideline.sideline.MsgSuccessTask", value: MsgSuccessTask.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSuccessTask: Could not create message: ' + e.message)
			}
		},
		
		msgSubmitTask({ value }: msgSubmitTaskParams): EncodeObject {
			try {
				return { typeUrl: "/sideline.sideline.MsgSubmitTask", value: MsgSubmitTask.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSubmitTask: Could not create message: ' + e.message)
			}
		},
		
		msgStartJudgeTask({ value }: msgStartJudgeTaskParams): EncodeObject {
			try {
				return { typeUrl: "/sideline.sideline.MsgStartJudgeTask", value: MsgStartJudgeTask.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgStartJudgeTask: Could not create message: ' + e.message)
			}
		},
		
		msgCancelTask({ value }: msgCancelTaskParams): EncodeObject {
			try {
				return { typeUrl: "/sideline.sideline.MsgCancelTask", value: MsgCancelTask.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCancelTask: Could not create message: ' + e.message)
			}
		},
		
		msgDoTask({ value }: msgDoTaskParams): EncodeObject {
			try {
				return { typeUrl: "/sideline.sideline.MsgDoTask", value: MsgDoTask.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDoTask: Could not create message: ' + e.message)
			}
		},
		
		msgFailTask({ value }: msgFailTaskParams): EncodeObject {
			try {
				return { typeUrl: "/sideline.sideline.MsgFailTask", value: MsgFailTask.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgFailTask: Could not create message: ' + e.message)
			}
		},
		
		msgRegistEmployer({ value }: msgRegistEmployerParams): EncodeObject {
			try {
				return { typeUrl: "/sideline.sideline.MsgRegistEmployer", value: MsgRegistEmployer.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRegistEmployer: Could not create message: ' + e.message)
			}
		},
		
		msgCreateTask({ value }: msgCreateTaskParams): EncodeObject {
			try {
				return { typeUrl: "/sideline.sideline.MsgCreateTask", value: MsgCreateTask.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateTask: Could not create message: ' + e.message)
			}
		},
		
		msgUndoneTask({ value }: msgUndoneTaskParams): EncodeObject {
			try {
				return { typeUrl: "/sideline.sideline.MsgUndoneTask", value: MsgUndoneTask.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUndoneTask: Could not create message: ' + e.message)
			}
		},
		
		msgVoteTask({ value }: msgVoteTaskParams): EncodeObject {
			try {
				return { typeUrl: "/sideline.sideline.MsgVoteTask", value: MsgVoteTask.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgVoteTask: Could not create message: ' + e.message)
			}
		},
		
		msgFeedbackTask({ value }: msgFeedbackTaskParams): EncodeObject {
			try {
				return { typeUrl: "/sideline.sideline.MsgFeedbackTask", value: MsgFeedbackTask.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgFeedbackTask: Could not create message: ' + e.message)
			}
		},
		
		msgRegistDeveloper({ value }: msgRegistDeveloperParams): EncodeObject {
			try {
				return { typeUrl: "/sideline.sideline.MsgRegistDeveloper", value: MsgRegistDeveloper.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRegistDeveloper: Could not create message: ' + e.message)
			}
		},
		
		msgJudgeTask({ value }: msgJudgeTaskParams): EncodeObject {
			try {
				return { typeUrl: "/sideline.sideline.MsgJudgeTask", value: MsgJudgeTask.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgJudgeTask: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			SidelineSideline: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;